# Data Cleaning & Standarization

## Importing data

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_excel('regression_data.xls')
pd.set_option("display.max_columns", None)
#pd.set_option("display.max_rows", None)
df.head()

,id,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price
0,7129300520,2014-10-13,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,221900
1,6414100192,2014-12-09,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639,538000
2,5631500400,2015-02-25,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062,180000
3,2487200875,2014-12-09,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000,604000
4,1954400510,2015-02-18,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503,510000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21597 entries, 0 to 21596
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21597 non-null  int64
 1   date           21597 non-null  datetime64[ns]
 2   bedrooms       21597 non-null  int64
 3   bathrooms      21597 non-null  float64
 4   sqft_living    21597 non-null  int64
 5   sqft_lot       21597 non-null  int64
 6   floors         21597 non-null  float64
 7   waterfront     21597 non-null  int64
 8   view           21597 non-null  int64
 9   condition      21597 non-null  int64
 10  grade          21597 non-null  int64
 11  sqft_above     21597 non-null  int64
 12  sqft_basement  21597 non-null  int64
 13  yr_built       21597 non-null  int64
 14  yr_renovated   21597 non-null  int64
 15  zipcode        21597 non-null  int64
 16  lat            21597 non-null  float64
 17  long           21597 non-null  float64
 18  sqft_living15  21597 non-null  int64
 19  sqft_lot15     21597 non-null  int64
 20  price          21597 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(16)
memory usage: 3.5 MB

In [4]:
df.describe()

,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price
count,2.159700e+04,21597.000000,21597.000000,21597.000000,2.159700e+04,21597.000000,21597.000000,21597.000000,21597.000000,21597.000000,21597.000000,21597.000000,21597.000000,21597.000000,21597.000000,21597.000000,21597.000000,21597.000000,21597.000000,2.159700e+04
mean,4.580474e+09,3.373200,2.115826,2080.321850,1.509941e+04,1.494096,0.007547,0.234292,3.409825,7.657915,1788.596842,291.725008,1970.999676,84.464787,98077.951845,47.560093,-122.213982,1986.620318,12758.283512,5.402966e+05
std,2.876736e+09,0.926299,0.768984,918.106125,4.141264e+04,0.539683,0.086549,0.766390,0.650546,1.173200,827.759761,442.667800,29.375234,401.821438,53.513072,0.138552,0.140724,685.230472,27274.441950,3.673681e+05
min,1.000102e+06,1.000000,0.500000,370.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,3.000000,370.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000,7.800000e+04
25%,2.123049e+09,3.000000,1.750000,1430.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471100,-122.328000,1490.000000,5100.000000,3.220000e+05
50%,3.904930e+09,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.231000,1840.000000,7620.000000,4.500000e+05
75%,7.308900e+09,4.000000,2.500000,2550.000000,1.068500e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000,6.450000e+05
max,9.900000e+09,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000,7.700000e+06

## Checking Null Values

In [5]:
df.isnull().sum()

id               0
date             0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
price            0
dtype: int64

In [6]:
df.notnull().sum() # We haven't detected null values in any columns

id               21597
date             21597
bedrooms         21597
bathrooms        21597
sqft_living      21597
sqft_lot         21597
floors           21597
waterfront       21597
view             21597
condition        21597
grade            21597
sqft_above       21597
sqft_basement    21597
yr_built         21597
yr_renovated     21597
zipcode          21597
lat              21597
long             21597
sqft_living15    21597
sqft_lot15       21597
price            21597
dtype: int64

In [7]:
df.id.duplicated().sum() #checking how many duplicated ids(Houses) are there in the Data set

177

In [8]:
df.duplicated().sum() #Checking if there are duplicated rows. There are not any identical rows so the duplicated Ids may have some difference.

0

In [9]:
df.loc[df.id.duplicated(),:].sort_values(by=['id']) # We check all the duplicated Ids in the Dataframe

,id,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price
2495,1000102,2015-04-22,6,3.00,2400,9373,2.0,0,0,3,7,2400,0,1991,0,98002,47.3262,-122.214,2060,7316,300000
16801,7200179,2015-04-24,2,1.00,840,12750,1.0,0,0,3,6,840,0,1925,0,98055,47.4840,-122.211,1480,6969,175000
11422,109200390,2014-10-20,3,1.75,1480,3900,1.0,0,0,4,7,1480,0,1980,0,98023,47.2977,-122.367,1830,6956,250000
12406,123039336,2014-12-08,1,1.00,620,8261,1.0,0,0,3,5,620,0,1939,0,98106,47.5138,-122.364,1180,8244,244900
7786,251300110,2015-01-14,3,2.25,2510,12013,2.0,0,0,3,8,2510,0,1988,0,98003,47.3473,-122.314,1870,8017,358000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2492,9407110710,2015-02-26,3,1.75,1510,8400,1.0,0,0,2,7,980,530,1979,0,98045,47.4476,-121.771,1500,10125,322000
4918,9809000020,2015-03-13,5,2.25,3120,16672,2.0,0,0,4,9,3120,0,1969,0,98004,47.6458,-122.219,3740,17853,1940000
6340,9828200460,2015-01-06,2,1.00,700,4800,1.0,0,0,3,7,700,0,1922,0,98122,47.6147,-122.300,1440,4800,430000
15186,9834200305,2015-02-10,3,1.00,1790,3876,1.5,0,0,5,7,1090,700,1904,0,98144,47.5750,-122.288,1360,4080,615000
1085,9834200885,2015-04-20,4,2.50,2080,4080,1.0,0,0,5,7,1040,1040,1962,0,98144,47.5720,-122.290,1340,4080,550000

In [10]:
df.loc[df['id']==7853400250]

,id,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price
20164,7853400250,2014-06-04,4,3.5,2910,5260,2.0,0,0,3,9,2910,0,2012,0,98065,47.5168,-121.883,2910,5260,610000
20165,7853400250,2015-02-19,4,3.5,2910,5260,2.0,0,0,3,9,2910,0,2012,0,98065,47.5168,-121.883,2910,5260,645000

In [11]:
df=df.sort_values('date')

In [12]:
df.head()

,id,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price
7316,2202500290,2014-05-02,4,1.0,1450,8800,1.0,0,0,4,7,1450,0,1954,0,98006,47.5746,-122.135,1260,8942,435000
20586,7853361370,2014-05-02,4,2.5,3310,6500,2.0,0,0,3,8,3310,0,2012,0,98065,47.5150,-121.870,2380,5000,555000
1040,7197300105,2014-05-02,4,2.5,1940,10500,1.0,0,0,4,7,1140,800,1976,0,98052,47.6830,-122.114,2200,10500,550000
20543,3438501320,2014-05-02,2,2.5,1630,1368,2.0,0,0,3,7,1280,350,2009,0,98106,47.5489,-122.363,1590,2306,295000
9587,472000620,2014-05-02,3,2.5,2600,4750,1.0,0,0,4,9,1700,900,1951,0,98117,47.6833,-122.400,2380,4750,790000

In [13]:
df2 = df.drop('price', axis=1)

In [14]:
df2.duplicated().sum()

0

In [15]:
pd.set_option("display.max_rows", None)
df[df.duplicated(['id'], keep=False)].sort_values(by=['id'])

,id,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price
2495,1000102,2015-04-22,6,3.00,2400,9373,2.0,0,0,3,7,2400,0,1991,0,98002,47.3262,-122.214,2060,7316,300000
2494,1000102,2014-09-16,6,3.00,2400,9373,2.0,0,0,3,7,2400,0,1991,0,98002,47.3262,-122.214,2060,7316,280000
16800,7200179,2014-10-16,2,1.00,840,12750,1.0,0,0,3,6,840,0,1925,0,98055,47.4840,-122.211,1480,6969,150000
16801,7200179,2015-04-24,2,1.00,840,12750,1.0,0,0,3,6,840,0,1925,0,98055,47.4840,-122.211,1480,6969,175000
11421,109200390,2014-08-20,3,1.75,1480,3900,1.0,0,0,4,7,1480,0,1980,0,98023,47.2977,-122.367,1830,6956,245000
11422,109200390,2014-10-20,3,1.75,1480,3900,1.0,0,0,4,7,1480,0,1980,0,98023,47.2977,-122.367,1830,6956,250000
12406,123039336,2014-12-08,1,1.00,620,8261,1.0,0,0,3,5,620,0,1939,0,98106,47.5138,-122.364,1180,8244,244900
12405,123039336,2014-06-11,1,1.00,620,8261,1.0,0,0,3,5,620,0,1939,0,98106,47.5138,-122.364,1180,8244,148000
7785,251300110,2014-07-31,3,2.25,2510,12013,2.0,0,0,3,8,2510,0,1988,0,98003,47.3473,-122.314,1870,8017,225000
7786,251300110,2015-01-14,3,2.25,2510,12013,2.0,0,0,3,8,2510,0,1988,0,98003,47.3473,-122.314,1870,8017,358000
9225,302000375,2014-08-14,3,2.00,1050,18304,1.0,0,0,4,7,1050,0,1953,0,98001,47.3206,-122.269,1690,15675,169100
9226,302000375,2015-05-06,3,2.00,1050,18304,1.0,0,0,4,7,1050,0,1953,0,98001,47.3206,-122.269,1690,15675,250000
14841,324000530,2014-07-08,3,1.00,1320,5000,1.5,0,0,3,7,1320,0,1912,0,98116,47.5711,-122.386,1320,4179,201500
14842,324000530,2015-03-23,3,1.00,1320,5000,1.5,0,0,3,7,1320,0,1912,0,98116,47.5711,-122.386,1320,4179,459000
7171,526059224,2014-09-23,4,1.75,1650,7276,1.0,0,0,3,7,1010,640,1977,0,98011,47.7721,-122.206,1840,8550,260000
7172,526059224,2015-02-06,4,1.75,1650,7276,1.0,0,0,3,7,1010,640,1977,0,98011,47.7721,-122.206,1840,8550,470000
17367,641900050,2014-08-19,4,2.25,2160,8817,1.0,0,0,3,7,1460,700,1965,0,98133,47.7595,-122.356,1880,8817,335000
17368,641900050,2015-02-06,4,2.25,2160,8817,1.0,0,0,3,7,1460,700,1965,0,98133,47.7595,-122.356,1880,8817,499950
19536,643300040,2014-11-04,4,1.75,1920,9500,1.0,0,0,4,7,1470,450,1966,0,98006,47.5683,-122.177,1820,10091,481000
19537,643300040,2015-03-13,4,1.75,1920,9500,1.0,0,0,4,7,1470,450,1966,0,98006,47.5683,-122.177,1820,10091,719521
15285,705730280,2014-08-19,3,2.50,1740,5267,2.0,0,0,3,7,1740,0,1999,0,98038,47.3777,-122.023,2180,5000,325000
15286,705730280,2015-04-21,3,2.50,1740,5267,2.0,0,0,3,7,1740,0,1999,0,98038,47.3777,-122.023,2180,5000,335000
9267,722039087,2015-05-04,2,1.00,990,57499,1.0,0,0,2,6,990,0,1949,0,98070,47.4145,-122.463,2090,27442,329000
9266,722039087,2014-09-23,2,1.00,990,57499,1.0,0,0,2,6,990,0,1949,0,98070,47.4145,-122.463,2090,27442,220500
3782,723049156,2014-11-12,3,1.00,1700,8645,1.0,0,0,3,6,1700,0,1955,0,98146,47.4899,-122.337,1500,7980,284700
3781,723049156,2014-05-23,3,1.00,1700,8645,1.0,0,0,3,6,1700,0,1955,0,98146,47.4899,-122.337,1500,7980,149000
824,726049190,2015-02-18,3,1.00,1810,7200,1.0,0,0,4,7,1130,680,1954,0,98133,47.7493,-122.351,1810,8100,431000
823,726049190,2014-10-02,3,1.00,1810,7200,1.0,0,0,4,7,1130,680,1954,0,98133,47.7493,-122.351,1810,8100,287500
17589,795000620,2014-12-15,3,1.00,1080,6250,1.0,0,0,2,5,1080,0,1950,0,98168,47.5045,-122.330,1070,6250,124000
17588,795000620,2014-09-24,3,1.00,1080,6250,1.0,0,0,2,5,1080,0,1950,0,98168,47.5045,-122.330,1070,6250,115000
17590,795000620,2015-03-11,3,1.00,1080,6250,1.0,0,0,2,5,1080,0,1950,0,98168,47.5045,-122.330,1070,6250,157000
13679,937000330,2014-12-24,3,1.50,1170,11530,1.0,0,0,3,7,1170,0,1960,0,98198,47.4211,-122.290,1550,8605,157000
13680,937000330,2015-03-19,3,1.50,1170,11530,1.0,0,0,3,7,1170,0,1960,0,98198,47.4211,-122.290,1550,8605,246500
12054,1036400200,2015-04-29,4,1.75,1670,13125,1.0,0,0,5,8,1670,0,1973,0,98052,47.6315,-122.101,2360,12500,697000
12053,1036400200,2015-02-13,4,1.75,1670,13125,1.0,0,0,5,8,1670,0,1973,0,98052,47.6315,-122.101,2360,12500,661000
11183,1139600270,2015-03-24,3,2.75,2090,9620,1.0,0,0,3,8,1340,750,1987,0,98023,47.2741,-122.337,2150,9660,310000
11182,1139600270,2014-07-01,3,2.75,2090,9620,1.0,0,0,3,8,1340,750,1987,0,98023,47.2741,-122.337,2150,9660,300000
12422,1217000340,2014-06-06,3,1.00,1840,8100,1.0,0,0,4,7,920,920,1953,0,98166,47.4550,-122.350,1250,8100,185000
12423,1217000340,2015-02-19,3,1.00,1840,8100,1.0,0,0,4,7,920,920,1953,0,98166,47.4550,-122.350,1250,8100,340000
9866,1219000473,2015-03-23,3,1.75,1570,15330,1.0,0,0,3,7,1080,490,1956,0,98166,47.4608,-122.340,1250,13330,371000
9865,1219000473,2014-06-26,3,1.75,1570,15330,1.0,0,0,3,7,1080,490,1956,0,98166,47.4608,-122.340,1250,13330,164950
1200,1231000510,2014-09-22,3,1.75,1490,3800,1.0,0,0,3,6,700,790,1913,0,98118,47.5554,-122.270,2180,4000,263000
1201,1231000510,2015-05-04,3,1.75,1490,3800,1.0,0,0,3,6,700,790,1913,0,98118,47.5554,-122.270,2180,4000,510000
2530,1232000810,2015-03-26,3,2.50,1400,4800,1.0,0,0,3,7,1200,200,1921,0,98117,47.6865,-122.379,1440,3840,537000
2529,1232000810,2014-09-12,3,2.50,1400,4800,1.0,0,0,3,7,1200,200,1921,0,98117,47.6865,-122.379,1440,3840,340000
8496,1237500540,2014-10-21,3,1.75,1370,10866,1.0,0,0,4,6,1370,0,1945,0,98052,47.6774,-122.164,1580,14250,225000
8497,1237500540,2014-12-22,3,1.75,1370,10866,1.0,0,0,4,6,1370,0,1945,0,98052,47.6774,-122.164,1580,14250,270000
14208,1250201165,2015-03-17,5,2.50,2000,3600,1.0,0,0,3,6,1150,850,1987,0,98144,47.5971,-122.295,1410,3600,474500
14207,1250201165,2014-11-21,5,2.50,2000,3600,1.0,0,0,3,6,1150,850,1987,0,98144,47.5971,-122.295,1410,3600,441000
3752,1254200015,2014-12-16,3,2.50,2260,5500,1.5,0,0,3,7,1280,980,1910,0,98117,47.6810,-122.388,1790,5355,405000
3753,1254200015,2015-04-08,3,2.50,2260,5500,1.5,0,0,3,7,1280,980,1910,0,98117,47.6810,-122.388,1790,5355,625000
17567,1423049019,2015-03-31,2,1.00,580,7500,1.0,0,0,3,5,580,0,1943,0,98178,47.4852,-122.251,1700,11250,220000
17566,1423049019,2014-05-23,2,1.00,580,7500,1.0,0,0,3,5,580,0,1943,0,98178,47.4852,-122.251,1700,11250,90000
14560,1432400120,2014-11-11,3,1.00,1010,7690,1.0,0,0,4,6,1010,0,1958,0,98058,47.4501,-122.176,1010,7619,165000
14561,1432400120,2015-05-08,3,1.00,1010,7690,1.0,0,0,4,6,1010,0,1958,0,98058,47.4501,-122.176,1010,7619,255000
7238,1446403850,2014-09-16,2,1.00,790,7153,1.0,0,0,4,6,790,0,1944,0,98168,47.4869,-122.324,810,7128,118125
7239,1446403850,2015-01-14,2,1.00,790,7153,1.0,0,0,4,6,790,0,1944,0,98168,47.4869,-122.324,810,7128,212000
10261,1450100390,2014-09-05,3,1.00,920,7314,1.0,0,0,3,6,920,0,1960,0,98002,47.2892,-122.220,1010,7420,125000
10262,1450100390,2015-03-16,3,1.00,920,7314,1.0,0,0,3,6,920,0,1960,0,98002,47.2892,-122.220,1010,7420,208000
13171,1523049207,2015-01-14,4,2.00,1700,8043,1.0,0,0,3,7,850,850,1954,0,98168,47.4758,-122.288,1540,13260,220000
13170,1523049207,2014-08-05,4,2.00,1700,8043,1.0,0,0,3,7,850,850,1954,0,98168,47.4758,-122.288,1540,13260,161000
4868,1524079093,2015-03-18,3,1.75,1300,20700,1.0,0,0,3,7,1300,0,1962,0,98024,47.5587,-121.904,1930,37638,369500
4867,1524079093,2014-08-27,3,1.75,1300,20700,1.0,0,0,3,7,1300,0,1962,0,98024,47.5587,-121.904,1930,37638,275000
5967,1545800290,2015-04-08,4,2.50,1700,6675,2.0,0,0,3,7,1700,0,1997,0,98038,47.3638,-122.053,1570,7540,315000
5966,1545800290,2014-09-05,4,2.50,1700,6675,2.0,0,0,3,7,1700,0,1997,0,98038,47.3638,-122.053,1570,7540,215000
9106,1568100300,2015-01-21,6,4.50,3500,8504,2.0,0,0,3,7,3500,0,1980,0,98155,47.7351,-122.295,1550,8460,682500
9105,1568100300,2014-09-17,6,4.50,3500,8504,2.0,0,0,3,7,3500,0,1980,0,98155,47.7351,-122.295,1550,8460,350000
17750,1630700361,2015-04-09,4,1.75,2860,48351,1.0,0,0,3,8,1710,1150,1978,0,98077,47.7605,-122.085,2460,43560,583500
17749,1630700361,2014-06-27,4,1.75,2860,48351,1.0,0,0,3,8,1710,1150,1978,0,98077,47.7605,-122.085,2460,43560,530000
8427,1721801010,2015-04-24,3,1.00,1790,6120,1.0,0,0,3,6,1790,0,1937,1964,98146,47.5080,-122.337,830,6120,302100
8426,1721801010,2014-09-03,3,1.00,1790,6120,1.0,0,0,3,6,1790,0,1937,1964,98146,47.5080,-122.337,830,6120,225000
2500,1781500435,2014-08-20,3,1.75,1580,7344,1.0,0,0,5,7,1580,0,1911,0,98126,47.5256,-122.380,1580,6207,260000
2501,1781500435,2015-02-25,3,1.75,1580,7344,1.0,0,0,5,7,1580,0,1911,0,98126,47.5256,-122.380,1580,6207,575000
5718,1788800630,2014-10-29,3,1.00,840,12091,1.0,0,0,3,6,840,0,1959,0,98023,47.3281,-122.343,840,9324,96500
5719,1788800630,2015-02-25,3,1.00,840,12091,1.0,0,0,3,6,840,0,1959,0,98023,47.3281,-122.343,840,9324,185000
13743,1788900230,2014-07-22,3,1.00,840,9480,1.0,0,0,3,6,840,0,1960,0,98023,47.3277,-122.341,840,9420,86500
13744,1788900230,2015-04-03,3,1.00,840,9480,1.0,0,0,3,6,840,0,1960,0,98023,47.3277,-122.341,840,9420,199950
3536,1823049202,2014-06-10,6,1.50,1930,8400,1.0,0,0,3,7,1030,900,1971,0,98146,47.4869,-122.340,1780,9520,175000
3537,1823049202,2015-01-07,6,1.50,1930,8400,1.0,0,0,3,7,1030,900,1971,0,98146,47.4869,-122.340,1780,9520,326000
3946,1825069031,2014-08-14,4,1.75,2410,8447,2.0,0,3,4,8,2060,350,1936,1980,98074,47.6499,-122.088,2520,14789,550000
3947,1825069031,2014-10-16,4,1.75,2410,8447,2.0,0,3,4,8,2060,350,1936,1980,98074,47.6499,-122.088,2520,14789,550000
19194,1901600090,2014-06-26,5,1.75,1940,6654,1.5,0,0,4,7,1940,0,1953,0,98166,47.4663,-122.359,2300,9500,359000
19195,1901600090,2015-04-26,5,1.75,1940,6654,1.5,0,0,4,7,1940,0,1953,0,98166,47.4663,-122.359,2300,9500,390000
9111,1922059278,2014-10-14,3,1.00,1010,11880,1.0,0,0,3,7,1010,0,1960,0,98030,47.3762,-122.219,1150,9435,145000
9112,1922059278,2015-03-05,3,1.00,1010,11880,1.0,0,0,3,7,1010,0,1960,0,98030,47.3762,-122.219,1150,9435,255000
5754,1954420170,2014-11-13,3,2.50,2150,7484,2.0,0,0,3,8,2150,0,1988,0,98074,47.6191,-122.043,2150,6879,580000
5753,1954420170,2014-05-21,3,2.50,2150,7484,2.0,0,0,3,8,2150,0,1988,0,98074,47.6191,-122.043,2150,6879,368250
17276,1974300020,2014-08-27,4,2.50,2270,11500,1.0,0,0,3,8,1540,730,1967,0,98034,47.7089,-122.241,2020,10918,380000
17277,1974300020,2015-02-18,4,2.50,2270,11500,1.0,0,0,3,8,1540,730,1967,0,98034,47.7089,-122.241,2020,10918,624900
10246,1995200200,2014-05-06,3,1.00,1510,6083,1.0,0,0,4,6,860,650,1940,0,98115,47.6966,-122.324,1510,5712,313950
10247,1995200200,2014-10-08,3,1.00,1510,6083,1.0,0,0,4,6,860,650,1940,0,98115,47.6966,-122.324,1510,5712,415000
12942,2019200220,2014-09-23,3,2.25,1470,8682,1.0,0,0,3,7,1160,310,1985,0,98003,47.2729,-122.299,1670,8359,160000
12943,2019200220,2015-02-26,3,2.25,1470,8682,1.0,0,0,3,7,1160,310,1985,0,98003,47.2729,-122.299,1670,8359,269000
13615,2023049218,2014-07-16,2,1.00,930,7740,1.0,0,0,1,5,930,0,1932,0,98148,47.4611,-122.324,1620,8584,105500
13616,2023049218,2015-03-16,2,1.00,930,7740,1.0,0,0,1,5,930,0,1932,0,98148,47.4611,-122.324,1620,8584,445000
15787,2044500213,2014-06-17,4,2.00,1870,6000,1.5,0,0,3,7,1870,0,1956,0,98125,47.7155,-122.315,1520,7169,310000
15788,2044500213,2015-01-26,4,2.00,1870,6000,1.5,0,0,3,7,1870,0,1956,0,98125,47.7155,-122.315,1520,7169,449000
1863,2143700830,2015-03-12,4,2.50,2100,19680,1.5,0,0,3,6,2100,0,1914,0,98055,47.4787,-122.230,1340,12300,370000
1862,2143700830,2014-10-06,4,2.50,2100,19680,1.5,0,0,3,6,2100,0,1914,0,98055,47.4787,-122.230,1340,12300,207000
8005,2206700215,2015-04-22,4,2.00,2070,9822,1.0,0,0,5,7,2070,0,1955,0,98006,47.5660,-122.140,1300,9572,550000
8004,2206700215,2014-08-22,4,2.00,2070,9822,1.0,0,0,5,7,2070,0,1955,0,98006,47.5660,-122.140,1300,9572,375000
9383,2212200100,2014-10-22,4,2.50,2150,7670,1.0,0,0,5,7,1240,910,1976,0,98031,47.3942,-122.189,1610,7350,229950
9384,2212200100,2015-04-22,4,2.50,2150,7670,1.0,0,0,5,7,1240,910,1976,0,98031,47.3942,-122.189,1610,7350,344900
1448,2228900270,2014-08-12,2,1.00,1010,6000,1.0,0,0,4,6,1010,0,1944,0,98133,47.7710,-122.353,1610,7313,215000
1449,2228900270,2015-02-12,2,1.00,1010,6000,1.0,0,0,4,6,1010,0,1944,0,98133,47.7710,-122.353,1610,7313,302000
371,2231500030,2014-10-01,4,2.25,2180,10754,1.0,0,0,5,7,1100,1080,1954,0,98133,47.7711,-122.341,1810,6929,315000
372,2231500030,2015-03-24,4,2.25,2180,10754,1.0,0,0,5,7,1100,1080,1954,0,98133,47.7711,-122.341,1810,6929,530000
10242,2422049104,2014-09-15,2,1.00,830,9000,1.0,0,0,3,6,830,0,1939,0,98032,47.3813,-122.243,1160,7680,85000
10243,2422049104,2014-12-30,2,1.00,830,9000,1.0,0,0,3,6,830,0,1939,0,98032,47.3813,-122.243,1160,7680,235000
17266,2473380920,2014-08-13,5,2.50,1720,10202,1.5,0,0,3,7,1720,0,1970,0,98058,47.4572,-122.167,1720,8478,206325
17267,2473380920,2015-02-27,5,2.50,1720,10202,1.5,0,0,3,7,1720,0,1970,0,98058,47.4572,-122.167,1720,8478,339000
15554,2560801222,2014-06-18,3,2.25,1990,6350,2.0,0,0,3,7,1990,0,1967,0,98198,47.3822,-122.316,1220,6250,180000
15555,2560801222,2014-11-13,3,2.25,1990,6350,2.0,0,0,3,7,1990,0,1967,0,98198,47.3822,-122.316,1220,6250,309950
15987,2561340020,2015-02-17,3,1.75,1780,11096,1.0,0,0,3,7,1210,570,1979,0,98074,47.6170,-122.051,1780,10640,500000
15986,2561340020,2014-08-04,3,1.75,1780,11096,1.0,0,0,3,7,1210,570,1979,0,98074,47.6170,-122.051,1780,10640,325000
9712,2568300045,2015-03-19,6,2.00,1900,8240,1.0,0,0,2,7,1200,700,1964,0,98125,47.7037,-122.296,1900,8240,649950
9711,2568300045,2014-06-25,6,2.00,1900,8240,1.0,0,0,2,7,1200,700,1964,0,98125,47.7037,-122.296,1900,8240,305000
15264,2619920170,2014-12-19,4,2.50,3230,4290,2.0,0,0,3,9,3230,0,2004,0,98033,47.6874,-122.161,3220,5083,765000
15263,2619920170,2014-10-01,4,2.50,3230,4290,2.0,0,0,3,9,3230,0,2004,0,98033,47.6874,-122.161,3220,5083,772500
7841,2621600015,2015-04-30,3,1.00,1150,8924,1.0,0,0,3,6,1150,0,1943,0,98030,47.3865,-122.217,1492,8924,175000
7840,2621600015,2015-01-21,3,1.00,1150,8924,1.0,0,0,3,6,1150,0,1943,0,98030,47.3865,-122.217,1492,8924,120000
20597,2724049222,2014-12-01,2,2.50,1000,1092,2.0,0,0,3,7,990,10,2004,0,98118,47.5419,-122.271,1330,1466,220000
20596,2724049222,2014-08-02,2,2.50,1000,1092,2.0,0,0,3,7,990,10,2004,0,98118,47.5419,-122.271,1330,1466,163800
5587,2726049071,2014-12-11,2,1.00,820,4206,1.0,0,0,3,5,820,0,1949,0,98125,47.7076,-122.284,1810,7200,510000
5588,2726049071,2015-04-08,2,1.00,820,4206,1.0,0,0,3,5,820,0,1949,0,98125,47.7076,-122.284,1810,7200,489950
3619,2767602141,2014-09-05,3,1.50,1380,4290,1.0,0,0,3,7,1080,300,1955,0,98107,47.6740,-122.379,1510,3900,525000
3620,2767602141,2014-12-22,3,1.50,1380,4290,1.0,0,0,3,7,1080,300,1955,0,98107,47.6740,-122.379,1510,3900,650000
10598,2767603612,2014-05-12,2,2.25,1290,1334,3.0,0,0,3,8,1290,0,2007,0,98107,47.6719,-122.382,1350,1334,500000
10599,2767603612,2015-01-13,2,2.25,1290,1334,3.0,0,0,3,8,1290,0,2007,0,98107,47.6719,-122.382,1350,1334,489000
8118,2787460720,2015-02-27,3,2.00,1010,7896,1.0,0,0,3,7,1010,0,1984,0,98031,47.4046,-122.181,1540,7896,200000
8119,2787460720,2015-05-06,3,2.00,1010,7896,1.0,0,0,3,7,1010,0,1984,0,98031,47.4046,-122.181,1540,7896,259950
11763,2892700041,2014-07-14,3,1.50,1370,7439,1.0,0,0,4,6,1370,0,1963,0,98055,47.4499,-122.189,2350,3370,168000
11764,2892700041,2015-01-28,3,1.50,1370,7439,1.0,0,0,4,6,1370,0,1963,0,98055,47.4499,-122.189,2350,3370,238000
13605,3185600040,2014-12-24,2,1.00,1400,4500,1.0,0,0,3,7,900,500,1922,0,98055,47.4866,-122.219,1400,5500,310000
13604,3185600040,2014-05-22,2,1.00,1400,4500,1.0,0,0,3,7,900,500,1922,0,98055,47.4866,-122.219,1400,5500,180000
4074,3262300940,2015-02-10,3,1.00,1220,8119,1.0,0,0,4,7,1220,0,1955,0,98039,47.6328,-122.236,1910,8119,940000
4073,3262300940,2014-11-07,3,1.00,1220,8119,1.0,0,0,4,7,1220,0,1955,0,98039,47.6328,-122.236,1910,8119,875000
10957,3271300955,2014-07-03,4,2.50,2020,4350,2.0,0,0,5,9,1730,290,1943,0,98199,47.6503,-122.410,1620,5800,554729
10958,3271300955,2015-02-24,4,2.50,2020,4350,2.0,0,0,5,9,1730,290,1943,0,98199,47.6503,-122.410,1620,5800,868000
10210,3293700496,2014-08-14,4,1.75,1850,7730,1.0,0,0,5,7,1100,750,1956,0,98133,47.7481,-122.355,2260,8581,270000
10211,3293700496,2014-12-04,4,1.75,1850,7730,1.0,0,0,5,7,1100,750,1956,0,98133,47.7481,-122.355,2260,8581,450000
5240,3303000130,2015-04-28,3,2.25,1770,7667,1.0,0,0,3,8,1270,500,1966,0,98177,47.7724,-122.362,2180,8103,520000
5239,3303000130,2015-01-16,3,2.25,1770,7667,1.0,0,0,3,8,1270,500,1966,0,98177,47.7724,-122.362,2180,8103,370000
6624,3323059027,2014-05-28,3,2.75,1720,28000,1.0,0,0,4,7,1720,0,1958,0,98058,47.4375,-122.176,2000,41817,326000
6625,3323059027,2015-02-25,3,2.75,1720,28000,1.0,0,0,4,7,1720,0,1958,0,98058,47.4375,-122.176,2000,41817,340000
18747,3332000615,2014-10-20,3,1.00,1330,3740,1.5,0,0,3,6,1330,0,1903,0,98118,47.5502,-122.274,1330,5053,310000
18748,3332000615,2015-04-22,3,1.00,1330,3740,1.5,0,0,3,6,1330,0,1903,0,98118,47.5502,-122.274,1330,5053,389000
14353,3333002450,2014-07-08,1,1.00,850,8050,1.0,0,0,2,6,850,0,1906,0,98118,47.5427,-122.288,1590,5180,165000
14354,3333002450,2015-01-22,1,1.00,850,8050,1.0,0,0,2,6,850,0,1906,0,98118,47.5427,-122.288,1590,5180,490000
2036,3395040550,2014-07-28,3,2.50,1530,2890,2.0,0,0,3,7,1530,0,2001,0,98108,47.5434,-122.293,1540,2890,250000
2037,3395040550,2015-04-29,3,2.50,1530,2890,2.0,0,0,3,7,1530,0,2001,0,98108,47.5434,-122.293,1540,2890,320000
13647,3432501415,2014-11-11,3,1.75,1170,8148,1.0,0,0,3,7,1170,0,1952,0,98155,47.7479,-122.318,1200,8147,399000
13646,3432501415,2014-07-14,3,1.75,1170,8148,1.0,0,0,3,7,1170,0,1952,0,98155,47.7479,-122.318,1200,8147,265000
14470,3523069060,2014-11-07,3,1.75,1340,63597,1.0,0,0,4,7,1340,0,1963,0,98038,47.4379,-122.011,1950,87120,290000
14471,3523069060,2015-04-01,3,1.75,1340,63597,1.0,0,0,4,7,1340,0,1963,0,98038,47.4379,-122.011,1950,87120,415000
14295,3528000040,2015-03-26,3,3.25,5290,224442,2.0,0,0,4,11,4540,750,1988,0,98053,47.6671,-122.051,3750,84936,1800000
14294,3528000040,2014-10-01,3,3.25,5290,224442,2.0,0,0,4,11,4540,750,1988,0,98053,47.6671,-122.051,3750,84936,1690000
18688,3558900590,2014-11-25,6,1.75,2230,10080,1.0,0,0,3,7,1390,840,1969,0,98034,47.7089,-122.201,2110,8475,360000
18689,3558900590,2015-03-24,6,1.75,2230,10080,1.0,0,0,3,7,1390,840,1969,0,98034,47.7089,-122.201,2110,8475,692500
5689,3578401060,2014-12-16,3,2.25,1920,9672,2.0,0,0,4,8,1920,0,1984,0,98074,47.6233,-122.046,1950,10125,345000
5690,3578401060,2015-05-04,3,2.25,1920,9672,2.0,0,0,4,8,1920,0,1984,0,98074,47.6233,-122.046,1950,10125,625000
9811,3598600049,2015-04-24,1,0.75,840,7203,1.5,0,0,3,6,840,0,1949,0,98168,47.4756,-122.301,1560,8603,224000
9810,3598600049,2014-10-03,1,0.75,840,7203,1.5,0,0,3,6,840,0,1949,0,98168,47.4756,-122.301,1560,8603,124000
1463,3630120700,2015-01-07,3,3.25,3190,5283,2.0,0,0,3,9,3190,0,2007,0,98029,47.5534,-122.002,2950,5198,765000
1462,3630120700,2014-05-13,3,3.25,3190,5283,2.0,0,0,3,9,3190,0,2007,0,98029,47.5534,-122.002,2950,5198,757000
9008,3739500096,2015-05-05,3,2.00,1540,6000,1.0,0,0,4,6,1540,0,1953,0,98155,47.7372,-122.307,1490,8213,430000
9007,3739500096,2015-01-26,3,2.00,1540,6000,1.0,0,0,4,6,1540,0,1953,0,98155,47.7372,-122.307,1490,8213,229000
8267,3883800011,2014-11-05,3,1.00,860,10426,1.0,0,0,3,6,860,0,1954,0,98146,47.4987,-122.341,1140,11250,82000
8268,3883800011,2015-04-08,3,1.00,860,10426,1.0,0,0,3,6,860,0,1954,0,98146,47.4987,-122.341,1140,11250,219900
15593,3904100089,2014-08-01,3,1.75,1350,7370,1.0,0,0,4,6,1350,0,1912,0,98118,47.5336,-122.278,1440,6000,190000
15594,3904100089,2015-03-18,3,1.75,1350,7370,1.0,0,0,4,6,1350,0,1912,0,98118,47.5336,-122.278,1440,6000,300000
12376,3935900232,2014-09-29,3,1.00,920,5546,1.0,0,0,2,6,920,0,1928,0,98125,47.7114,-122.284,1300,5546,207000
12377,3935900232,2015-01-12,3,1.00,920,5546,1.0,0,0,2,6,920,0,1928,0,98125,47.7114,-122.284,1300,5546,237000
346,3969300030,2014-12-29,4,1.00,1000,7134,1.0,0,0,3,6,1000,0,1943,0,98178,47.4897,-122.240,1020,7138,239900
345,3969300030,2014-07-23,4,1.00,1000,7134,1.0,0,0,3,6,1000,0,1943,0,98178,47.4897,-122.240,1020,7138,165000
12196,4031000520,2014-07-08,1,2.00,1150,9812,1.0,0,0,4,7,1150,0,1962,0,98001,47.2951,-122.284,1200,9812,115000
12197,4031000520,2014-11-25,1,2.00,1150,9812,1.0,0,0,4,7,1150,0,1962,0,98001,47.2951,-122.284,1200,9812,227000
7838,4139420590,2014-05-20,4,3.50,4560,16643,1.0,0,3,3,12,2230,2330,1995,0,98006,47.5521,-122.115,4060,15177,1210000

In [16]:
df_dupl=df[df.duplicated(['id','bedrooms','bathrooms','sqft_living','sqft_lot','floors','waterfront','view','condition','grade', 'sqft_above','sqft_basement','yr_built','yr_renovated','zipcode','lat','long','sqft_living15', 'sqft_lot15'], keep=False)].sort_values(by=['id'])

In [17]:
df=df.drop_duplicates( subset=['id','bedrooms','bathrooms','sqft_living','sqft_lot','floors','waterfront','view','condition','grade', 'sqft_above','sqft_basement','yr_built','yr_renovated','zipcode','lat','long','sqft_living15', 'sqft_lot15'],keep='last')

In [18]:
df.info() # After checking the duplicate rows we decided to keep the rows with the last date. Besides price and date, there is no other id that has difference in it's  values.

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21420 entries, 7316 to 16580
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21420 non-null  int64
 1   date           21420 non-null  datetime64[ns]
 2   bedrooms       21420 non-null  int64
 3   bathrooms      21420 non-null  float64
 4   sqft_living    21420 non-null  int64
 5   sqft_lot       21420 non-null  int64
 6   floors         21420 non-null  float64
 7   waterfront     21420 non-null  int64
 8   view           21420 non-null  int64
 9   condition      21420 non-null  int64
 10  grade          21420 non-null  int64
 11  sqft_above     21420 non-null  int64
 12  sqft_basement  21420 non-null  int64
 13  yr_built       21420 non-null  int64
 14  yr_renovated   21420 non-null  int64
 15  zipcode        21420 non-null  int64
 16  lat            21420 non-null  float64
 17  long           21420 non-null  float64
 18  sqft_living15  21420 non-null  int64
 19  sqft_lot15     21420 non-null  int64
 20  price          21420 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(16)
memory usage: 3.6 MB

In [19]:
df.loc[df['id']==1000102]

,id,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price
2495,1000102,2015-04-22,6,3.0,2400,9373,2.0,0,0,3,7,2400,0,1991,0,98002,47.3262,-122.214,2060,7316,300000

In [20]:
df.loc[df['id']==7200179]

,id,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price
16801,7200179,2015-04-24,2,1.0,840,12750,1.0,0,0,3,6,840,0,1925,0,98055,47.484,-122.211,1480,6969,175000

In [21]:
df.loc[df['id']==109200390]

,id,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price
11422,109200390,2014-10-20,3,1.75,1480,3900,1.0,0,0,4,7,1480,0,1980,0,98023,47.2977,-122.367,1830,6956,250000

# Pre-processing

## Checking data types

In [22]:
df['bathrooms']=df['bathrooms'].astype(int) # Python by default floors the integer

In [23]:
df['floors']=df['floors'].astype(int)

In [24]:
df.head(15)

,id,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price
7316,2202500290,2014-05-02,4,1,1450,8800,1,0,0,4,7,1450,0,1954,0,98006,47.5746,-122.135,1260,8942,435000
20586,7853361370,2014-05-02,4,2,3310,6500,2,0,0,3,8,3310,0,2012,0,98065,47.5150,-121.870,2380,5000,555000
1040,7197300105,2014-05-02,4,2,1940,10500,1,0,0,4,7,1140,800,1976,0,98052,47.6830,-122.114,2200,10500,550000
20543,3438501320,2014-05-02,2,2,1630,1368,2,0,0,3,7,1280,350,2009,0,98106,47.5489,-122.363,1590,2306,295000
9587,472000620,2014-05-02,3,2,2600,4750,1,0,0,4,9,1700,900,1951,0,98117,47.6833,-122.400,2380,4750,790000
9578,1024069009,2014-05-02,5,2,2820,67518,2,0,0,3,8,2820,0,1979,0,98029,47.5794,-122.025,2820,48351,675000
11879,7305300695,2014-05-02,4,2,2820,8408,2,0,0,3,9,2820,0,2014,0,98155,47.7538,-122.325,1300,8408,625000
11895,3221059036,2014-05-02,4,2,3630,42884,1,0,0,3,9,2300,1330,1979,0,98092,47.2617,-122.190,2830,80148,400000
4959,7525000080,2014-05-02,3,1,2330,14892,1,0,0,3,8,1970,360,1980,0,98074,47.6267,-122.046,2570,14217,588500
3719,7739100015,2014-05-02,3,1,1710,7320,1,0,0,3,7,1710,0,1948,0,98155,47.7512,-122.281,2260,8839,463000
3710,6127600110,2014-05-02,4,2,1520,6200,1,0,0,3,7,1520,0,1945,0,98115,47.6780,-122.269,1910,6200,640000
17466,1525079056,2014-05-02,3,1,1800,23103,1,0,0,3,7,1800,0,1968,0,98014,47.6517,-121.906,1410,18163,284000
1391,5100401414,2014-05-02,2,1,880,6380,1,0,0,3,7,880,0,1938,1994,98115,47.6924,-122.322,1340,6380,490000
20133,2771102144,2014-05-02,3,3,1320,1327,2,0,0,3,8,1040,280,2008,0,98199,47.6506,-122.383,1440,1263,385000
14075,943100683,2014-05-02,3,2,1580,16215,1,0,0,4,7,1580,0,1978,0,98024,47.5643,-121.897,1450,16215,335000

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21420 entries, 7316 to 16580
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21420 non-null  int64
 1   date           21420 non-null  datetime64[ns]
 2   bedrooms       21420 non-null  int64
 3   bathrooms      21420 non-null  int64
 4   sqft_living    21420 non-null  int64
 5   sqft_lot       21420 non-null  int64
 6   floors         21420 non-null  int64
 7   waterfront     21420 non-null  int64
 8   view           21420 non-null  int64
 9   condition      21420 non-null  int64
 10  grade          21420 non-null  int64
 11  sqft_above     21420 non-null  int64
 12  sqft_basement  21420 non-null  int64
 13  yr_built       21420 non-null  int64
 14  yr_renovated   21420 non-null  int64
 15  zipcode        21420 non-null  int64
 16  lat            21420 non-null  float64
 17  long           21420 non-null  float64
 18  sqft_living15  21420 non-null  int64
 19  sqft_lot15     21420 non-null  int64
 20  price          21420 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(18)
memory usage: 3.6 MB

In [26]:
df=df.drop(['id'],axis=1)

In [ ]:
df.hist(figsize=(15,15),bins=20,layout=(5,4));

In [ ]:
df.hist(['bedrooms'], figsize=(13,11),bins=50)

In [ ]:
df.hist(['sqft_lot'], figsize=(13,11),bins=50)

In [ ]:
df.hist(['floors'], figsize=(13,11),bins=50)

In [ ]:
df.describe()

In [ ]:
df.sort_values(by=['bedrooms']).tail(10) 
# After checking visually, statistically and logically we assume that the maximun value of bedrooms is an outlier 
# and we think that's a typo since the price, the number of bathrooms is not coherent with so many bedrooms. 
# Probably we thought it is a 3 bedroom house instead of 33.

In [ ]:
df.sort_values(by=['bathrooms']).tail(10)

In [ ]:
df.sort_values(by=['sqft_living']).tail(10)

In [ ]:
df[df['zipcode']==98053].sort_values('price').head(10) #We checked the Zip code because the biggest sqft_living house was 
# cheaper than other similar in some features. We therefore checked the houses of that Zipcode 
# and we realised that in the district that house was the most expensive so we assume that is not an outlier 
# and that is a correct value.

In [ ]:
df.sort_values(by=['sqft_lot']).tail(10)

## Check useless columns

In [ ]:
corr_df=df.drop(['date','lat','long','yr_built','zipcode','yr_renovated','sqft_above','sqft_basement','sqft_lot','sqft_lot15','grade','condition','view','waterfront'], axis=1)

In [ ]:
#Correlation Matrix
corre_matrix=corr_df.corr()
corre_matrix

In [ ]:
#Heatmap
import matplotlib.pyplot as plt 
import seaborn as sns

mask=np.zeros_like(corre_matrix)
mask[np.triu_indices_from(mask)]=True
fig,ax = plt.subplots(figsize=(14,10))
ax=sns.heatmap(corre_matrix, mask=mask, center=0, cmap=sns.diverging_palette(220, 20, as_cmap=True), annot=True,);

In [ ]:
# checking the independent variables in front of the target variable (price) we can see some multicollinearity 
# between some of them, like sqft_above and sqft_living, or sqft_above and sqft_living15, or sqft_lot and sqft_living15.

In [ ]:
X_cat1=df[['condition','grade','view','waterfront']].astype(str)

In [ ]:
X_cat1.info()

In [ ]:
X_dummies1=pd.get_dummies(X_cat1, drop_first=True)
X_dummies1.head(10)

In [ ]:
X_cat2=df[['zipcode']].astype(str)
X_cat2.info()

In [ ]:
X_dummies2=pd.get_dummies(X_cat2, drop_first=True)
X_dummies2.head(10)

In [ ]:
X_dummies=pd.concat((X_dummies1,X_dummies2),axis=1)

In [ ]:
X_num=df[['bedrooms','bathrooms','sqft_living','floors','sqft_living15']]

In [ ]:
X_final=pd.concat((X_num,X_dummies),axis=1)

In [ ]:
X_final.head(10)

In [ ]:
y = df['price']

## Train test split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X_final,y,test_size=0.2,random_state=40)

## Linear regression model

In [ ]:
from sklearn import linear_model

In [ ]:
lm=linear_model.LinearRegression() #configure model
model=lm.fit(X_train,y_train)

In [ ]:
preds=lm.predict(X_test)
preds

## Model Validation

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [ ]:
r2_score(y_test,preds)

In [ ]:
mse=mean_squared_error(y_test, preds)
mse

In [ ]:
rmse=np.sqrt(mse)
rmse

In [ ]:
mean_absolute_error(y_test, preds)

In [ ]:
from xgboost import plot_importance
plt.rcParams["figure.figsize"] = (20, 15)
plot_importance(model,max_num_features=100)
plt.show()

In [ ]:
# TESTING-ADAPTING

from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import cross_val_predict

classifier_pipeline = make_pipeline(StandardScaler(), KNeighborsRegressor(n_neighbors=10))
y_pred = cross_val_predict(classifier_pipeline, X_final, y, cv=5)

from mlxtend.feature_selection import SequentialFeatureSelector as SFS
sfs1 = SFS(classifier_pipeline,
            k_features=1,
            forward=False,
            scoring='neg_mean_squared_error',
            cv=5)
sfs1.fit(X_final,y)
sfs1.subsets_

In [ ]:
df.var()